### ISSUE TITLE
[Feature request] Add a function to execute scripts in the pygg API

### ISSUE THREAD

**Issue by usslmuk** [l4tt/pygg#3]
### **Add a function to execute scripts in the Pygg API**

For example:

`exec(address, lua_script)`

Would be better as Pygg has been made to make externals

**Comment by l4tt** [comment]
Currently adding luavm to pygg, but you can't execute lua scripts in a game memory well point it to an address as that won't work. but you can execute lua scripts in pygg own env
![image](https://github.com/l4tt/pygg/assets/97377137/9b612a5e-cf22-46c7-906d-c5cdcc964ce4)

**Comment by l4tt** [comment]
[https://github.com/l4tt/pygg/blob/main/libs/luavm.py](url)
[https://github.com/l4tt/pygg/blob/main/libs/pygg_api.py](url)

Lua Vm args are now available for pygg
